# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ec928e399468c9c3392053571358ea4803c6f3915c1bb2c0e67f1a7ba9db099e79b0013ba62eecb31a74cf44b3818dd4b8e6715eff3b94f5d04a0b326fc93f6

test:
  secret_key_base: d875caedb8477e85d569d1e17850c504fdbe82133726db26146d45a91e5a5cd7051d2a8a6565e1a3bc34c061925be353f6aa84386842df66cbac4cd96bef2dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
